### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by garlic0x1** [webui-dev/webui#379]
I build the minimal C example like this:

```bash
git clone https://github.com/webui-dev/webui
cd webui/
make
cd examples/C/minimal/
make
```

Now I can run `./main`, the statically linked binary, just fine and a hello world shows up, but `./main-dyn` does not work.

```bash
garlic@garlic (~/c/webui/examples/C/minimal)
~> ./main-dyn 
Segmentation fault (core dumped)
```

Here is a stacktrace printed when I call `webui_show` from GDB:

```
Thread 1 "main-dyn" received signal SIGSEGV, Segmentation fault.
0x00007ffff7ea5a40 in g_signal_connect_data () from ./webui-2.so
(gdb) backtrace
#0  0x00007ffff7ea5a40 in g_signal_connect_data () at ./webui-2.so
#1  0x00007ffff700a579 in _gtk_modules_init.constprop.0 (gtk_modules_args=gtk_modules_args@entry=0x0, argv=0x0, argc=0x0) at ../gtk/gtk/gtkmodules.c:531
#2  0x00007ffff6de2c57 in do_post_parse_initialization (argc=0x0, argv=0x0) at ../gtk/gtk/gtkmain.c:763
#3  post_parse_hook (context=<optimized out>, group=<optimized out>, data=0x5555555c7ae0, error=0x7fffffffe180) at ../gtk/gtk/gtkmain.c:801
#4  0x00007ffff6a390e7 in g_option_context_parse
    (context=context@entry=0x5555555c7a80, argc=argc@entry=0x0, argv=argv@entry=0x0, error=error@entry=0x7fffffffe180) at ../glib/glib/goption.c:2067
#5  0x00007ffff6ddaab3 in gtk_parse_args (argc=0x0, argv=0x0) at ../gtk/gtk/gtkmain.c:1061
#6  0x00007ffff6de2a33 in gtk_init_check (argc=<optimized out>, argv=<optimized out>) at ../gtk/gtk/gtkmain.c:1107
#7  0x00007ffff6de417e in gtk_init (argc=<optimized out>, argv=<optimized out>) at ../gtk/gtk/gtkmain.c:1167
#8  0x00007ffff7e801d4 in _webui_wv_show () at ./webui-2.so
#9  0x00007ffff7e7ca3d in _webui_show_window () at ./webui-2.so
#10 0x00007ffff7e7c63e in _webui_show () at ./webui-2.so
#11 0x00007ffff7e74ed0 in webui_show () at ./webui-2.so
#12 0x0000555555555180 in ??? ()
#13 0x00007ffff7ca5c88 in __libc_start_call_main (main=main@entry=0x555555555159, argc=argc@entry=1, argv=argv@entry=0x7fffffffe4e8)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#14 0x00007ffff7ca5d4c in __libc_start_main_impl
    (main=0x555555555159, argc=1, argv=0x7fffffffe4e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe4d8)
    at ../csu/libc-start.c:360
#15 0x0000555555555085 in ??? ()
```

System:
Linux x86_64
GCC

**Comment by ttytm** [comment]
When I have time, I'll extend the workflow that it also includes spawning a window in CI an perfoming automated event tests. Similar to what the V repo already has. This should help to better detect if there is a regression.
